name: AppStoreApp

options:
  minimumXcodeGenVersion: 2.25.0
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: io.github.wacumov.appstoreapp
    VERSIONING_SYSTEM: "apple-generic"
    SWIFT_VERSION: 5.6
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: 1
  configs:
    Debug:
      SWIFT_COMPILATION_MODE: "singlefile"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_COMPILATION_MODE: "wholemodule"
      SWIFT_OPTIMIZATION_LEVEL: "-O"

fileGroups:
  - README.md

packages:
  AppStoreScraper:
    url: https://github.com/wacumov/app-store-scraper
    branch: main

targets:
  AppStoreApp:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    dependencies:
      - package: AppStoreScraper
